name: stockwaage_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

  firebase_auth: ^0.16.1
  firebase_core: ^0.4.5
  firebase_analytics: ^5.0.14
  cloud_firestore: ^0.13.6

  rxdart: ^0.24.1
  flutter_svg: ^0.17.4
  flutter_colorpicker: ^0.3.4
  fl_chart: ^0.10.1

  get_ip: ^0.4.0
  connectivity: ^0.4.8+6
  permission_handler: ^5.0.1+1
  shared_preferences: ^0.5.8

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/images/bees.png
    - assets/icons/menu.svg
    - assets/icons/emptyProfileIcon.png


  fonts:
    - family: bahnschrift
      fonts:
        - asset: assets/fonts/bahnschrift.TTF

    - family: segoe ui light
      fonts:
        - asset: assets/fonts/segoeuil.ttf

    - family: segoe ui semibold
      fonts:
        - asset: assets/fonts/seguisb.ttf

    - family: segoe ui
      fonts:
        - asset: assets/fonts/Segoe UI.ttf

    - family: century gothic
      fonts:
        - asset: assets/fonts/CenturyGothic.ttf